game_type: clonial
num_agent: 7
num_loc: 125
max_action: 58
num_step: 10  # TODO
num_map_tact: 182
powers: ['BRITAIN', 'CHINA', 'FRANCE', 'HOLLAND', 'JAPAN', 'RUSSIA', 'TURKEY']
board_feat : 35
order_feat : 269
msg_feat : 45
num_past_step : 40
curr_send : 43